'use strict';
const router = require('express').Router();
const { getDB } = require('../db');

// GET /api/capture/events?twinId=&limit=&offset=
router.get('/events', (req, res) => {
  const { twinId, limit = 500, offset = 0, sessionId } = req.query;
  const db = getDB();

  let sql = 'SELECT * FROM events WHERE 1=1';
  const params = [];
  if (twinId) { sql += ' AND twin_id=?'; params.push(twinId); }
  if (sessionId) { sql += ' AND session_id=?'; params.push(sessionId); }
  sql += ' ORDER BY captured_at DESC LIMIT ? OFFSET ?';
  params.push(parseInt(limit), parseInt(offset));

  const events = db.prepare(sql).all(...params).map(e => ({
    ...e,
    req_headers: JSON.parse(e.req_headers || '{}'),
    req_body:    e.req_body ? JSON.parse(e.req_body) : null,
    res_headers: JSON.parse(e.res_headers || '{}'),
    res_body:    e.res_body ? JSON.parse(e.res_body) : null,
    timing:      JSON.parse(e.timing || '{}'),
  }));

  res.json(events);
});

// GET /api/capture/export?format=har|json|openapi&twinId=
router.get('/export', (req, res) => {
  const { format = 'json', twinId, sessionId } = req.query;
  const db = getDB();

  const params = [];
  let sql = 'SELECT * FROM events WHERE 1=1';
  if (twinId) { sql += ' AND twin_id=?'; params.push(twinId); }
  if (sessionId) { sql += ' AND session_id=?'; params.push(sessionId); }
  sql += ' ORDER BY captured_at ASC';

  const rawEvents = db.prepare(sql).all(...params);
  const events = rawEvents.map(e => ({
    ...e,
    req_headers: JSON.parse(e.req_headers || '{}'),
    req_body:    e.req_body ? JSON.parse(e.req_body) : null,
    res_headers: JSON.parse(e.res_headers || '{}'),
    res_body:    e.res_body ? JSON.parse(e.res_body) : null,
    timing:      JSON.parse(e.timing || '{}'),
  }));

  const twin = twinId ? db.prepare('SELECT * FROM twins WHERE id=?').get(twinId) : null;
  const upstream = twin?.upstream || '';

  if (format === 'har') {
    res.setHeader('Content-Disposition', 'attachment; filename="capture.har"');
    res.setHeader('Content-Type', 'application/json');
    return res.json(_toHAR(events, upstream));
  }

  if (format === 'openapi') {
    res.setHeader('Content-Disposition', 'attachment; filename="openapi.json"');
    res.setHeader('Content-Type', 'application/json');
    return res.json(_toOpenAPI(events, twin?.name || 'Captured API', upstream));
  }

  // json (default)
  res.setHeader('Content-Disposition', 'attachment; filename="capture.json"');
  res.json(events);
});

// ── Helpers ───────────────────────────────────────────────────────────
function _toHAR(events, upstream) {
  return {
    log: {
      version: '1.2',
      creator: { name: 'TwinBridge', version: '1.0.0' },
      entries: events.map(e => ({
        startedDateTime: e.captured_at,
        time: e.latency_ms,
        request: {
          method: e.method, url: `${upstream}${e.path}`,
          httpVersion: 'HTTP/1.1',
          headers: _hdrs(e.req_headers),
          queryString: [],
          postData: e.req_body ? { mimeType: 'application/json', text: JSON.stringify(e.req_body) } : undefined,
          headersSize: -1, bodySize: e.req_body ? JSON.stringify(e.req_body).length : 0,
        },
        response: {
          status: e.status, statusText: String(e.status),
          httpVersion: 'HTTP/1.1',
          headers: _hdrs(e.res_headers),
          content: { mimeType: 'application/json', text: JSON.stringify(e.res_body), size: e.res_body ? JSON.stringify(e.res_body).length : 0 },
          redirectURL: '', headersSize: -1, bodySize: -1,
        },
        timings: {
          dns: e.timing.dns || -1, connect: e.timing.connect || -1,
          send: 0, wait: e.timing.ttfb || e.latency_ms, receive: e.timing.download || 0,
        },
      })),
    },
  };
}

function _hdrs(obj) {
  return Object.entries(obj || {}).map(([name, value]) => ({ name, value: String(value) }));
}

function _toOpenAPI(events, title, upstream) {
  const paths = {};
  for (const e of events) {
    const p = e.path.split('?')[0].replace(/\/[0-9a-f-]{20,}|\b\d{4,}\b/g, '/{id}');
    const method = e.method.toLowerCase();
    if (!paths[p]) paths[p] = {};
    if (!paths[p][method]) {
      paths[p][method] = {
        summary: `${e.method} ${p}`,
        responses: {},
        ...(e.req_body ? { requestBody: { content: { 'application/json': { schema: _inferSchema(e.req_body) } } } } : {}),
      };
    }
    if (!paths[p][method].responses[e.status]) {
      paths[p][method].responses[String(e.status)] = {
        description: e.status < 400 ? 'Success' : 'Error',
        ...(e.res_body ? { content: { 'application/json': { schema: _inferSchema(e.res_body) } } } : {}),
      };
    }
  }
  return {
    openapi: '3.0.0',
    info: { title, version: '1.0.0', description: `Generated by TwinBridge from ${events.length} captured events` },
    servers: upstream ? [{ url: upstream }] : [],
    paths,
  };
}

function _inferSchema(val, depth = 0) {
  if (depth > 3 || val == null) return {};
  if (typeof val === 'boolean') return { type: 'boolean', example: val };
  if (typeof val === 'number')  return { type: 'number',  example: val };
  if (typeof val === 'string')  return { type: 'string',  example: val };
  if (Array.isArray(val))       return { type: 'array', items: val[0] ? _inferSchema(val[0], depth+1) : {} };
  if (typeof val === 'object') {
    const props = {};
    for (const [k, v] of Object.entries(val)) props[k] = _inferSchema(v, depth+1);
    return { type: 'object', properties: props };
  }
  return {};
}

module.exports = router;
